name: "Rust Jira Action"
description: "Create a Jira issue from GitHub issue"

inputs:
  github_issue_title:
    required: true
    description: "Title of the GitHub issue"
  github_issue_body:
    required: false
    description: "Body of the GitHub issue"

runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build and run Rust CLI
      shell: bash
      run: run.sh "${{ inputs.github_issue_title }}" "${{ inputs.github_issue_body }}"
